---
# vars file for ocp4-post
dir: /home/ec2-user
var_app_node_label: application
var_artefact_storage_git_repo: git@example.com/ocp4-cluster-artifacts.git
files_to_encrypt:
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/.openshift_install_state.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfvars.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.aws.auto.tfvars.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeconfig"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeadmin-password"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.key"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.crt"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/metadata.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfstate"
files_to_archive:
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/.openshift_install_state.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/.openshift_install.log"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfvars.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.aws.auto.tfvars.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeconfig"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/auth/kubeadmin-password"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.key"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/tls/journal-gatewayd.crt"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/metadata.json"
    - "{{ dir }}/ocp/{{ var_cluster_base_domain }}/terraform.tfstate"
